export const Icons = {
  add: "add-outline",
  address: "home-outline",
  back: "arrow-back-outline",
  cart: "cart-outline",
  detail: "information-circle-outline",
  delete: "remove-circle",
  edit: "create",
  like: "heart",
  mail: "mail-outline",
  password: "lock-closed-outline",
  phone: "call-outline",
  profile: "person-circle",
  remove: "remove-outline",
  search: "search-outline",
  trash: "trash-outline",
  unlike: "heart-outline",
  user: "person-outline",
};
